/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tbd;

import tbd.DaftarStaff;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

public class DaftarStaff extends javax.swing.JFrame {

    /**
     * Creates new form DaftarStaff
     */
    public DaftarStaff() {
        initComponents();
        Connect();
        id_auto();
    }
    Connection kon;
    Statement stmt;
    ResultSet rs;
    PreparedStatement pst;  
    
    public void Connect() {
        String url = "jdbc:jtds:sqlserver://127.0.0.1:1433/SmartParking"; //buka =  nama database yang digunakan 
        try {       
            kon = DriverManager.getConnection(url, "kelompok3", "semangat");
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void id_auto(){
        try{
//             PreparedStatement stmt = kon.prepareStatement("SELECT * FROM Staff where IDStaff='"+value1+"'");
//            ResultSet res = stmt.executeQuery();
//            res = stmt.executeQuery();
            
//            pst = conn.prepareStatement("select * from Staff where Deleted=0");
//            rs = pst.executeQuery();
//           String sql = "select * from Staff order by IDStaff desc";
           pst = kon.prepareStatement("SELECT * from Staff order by IDStaff desc");
           rs = pst.executeQuery();
           txtNama.requestFocus();
           if (rs.next()) {
                String id = rs.getString("IDStaff").substring(1);
                String AN = "" + (Integer.parseInt(id) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "00";}
                else if(AN.length()==2)
                {Nol = "0";}
                

               txtIDStaff.setText("S" + Nol + AN);
            } else {
               txtIDStaff.setText("S001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDStaff = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtPosisi = new javax.swing.JTextField();
        txtKeterangan = new javax.swing.JTextField();
        jLabelSign = new javax.swing.JLabel();
        jLabelClear = new javax.swing.JLabel();
        jLabelMasuk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up Staff");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDStaff.setEditable(false);
        txtIDStaff.setBackground(new java.awt.Color(184, 51, 48));
        txtIDStaff.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtIDStaff.setForeground(new java.awt.Color(255, 255, 255));
        txtIDStaff.setBorder(null);
        txtIDStaff.setOpaque(false);
        getContentPane().add(txtIDStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 180, -1));

        txtNama.setBackground(new java.awt.Color(184, 51, 48));
        txtNama.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtNama.setForeground(new java.awt.Color(255, 255, 255));
        txtNama.setBorder(null);
        txtNama.setOpaque(false);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 180, 30));

        txtAlamat.setBackground(new java.awt.Color(184, 51, 48));
        txtAlamat.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamat.setBorder(null);
        txtAlamat.setOpaque(false);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 180, 30));

        txtPosisi.setBackground(new java.awt.Color(184, 51, 48));
        txtPosisi.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtPosisi.setForeground(new java.awt.Color(255, 255, 255));
        txtPosisi.setBorder(null);
        txtPosisi.setOpaque(false);
        txtPosisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPosisiKeyPressed(evt);
            }
        });
        getContentPane().add(txtPosisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 180, 30));

        txtKeterangan.setBackground(new java.awt.Color(184, 51, 48));
        txtKeterangan.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtKeterangan.setForeground(new java.awt.Color(255, 255, 255));
        txtKeterangan.setBorder(null);
        txtKeterangan.setOpaque(false);
        getContentPane().add(txtKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 180, 30));

        jLabelSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSignMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 130, 30));

        jLabelClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClearMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 120, 30));

        jLabelMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMasukMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Purple and Pink Flat Color Login (2).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void jLabelMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMasukMouseClicked
        Masuk obj = new Masuk();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_jLabelMasukMouseClicked

    private void jLabelClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMouseClicked
        txtNama.setText("");
        txtAlamat.setText("");
        txtPosisi.setText("");
        txtKeterangan.setText("");
        txtNama.requestFocus();
    }//GEN-LAST:event_jLabelClearMouseClicked

    private void jLabelSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSignMouseClicked
        String IDStaff = txtIDStaff.getText();
        String Nama = txtNama.getText();
        String Alamat = txtAlamat.getText();
        String Posisi = txtPosisi.getText();
        String Ket = txtKeterangan.getText();
        
        if(txtIDStaff.getText().equals("") || txtNama.getText().equals("") || txtAlamat.getText().equals("") || txtPosisi.getText().equals("") || txtKeterangan.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Masukkan data secara lengkap!");
        else { 
        try {
            pst = kon.prepareStatement("insert into Staff(IDStaff, NamaStaff, Alamat, Posisi, Keterangan, Deleted)values(?,?,?,?,?,0)");
            pst.setString(1, IDStaff);
            pst.setString(2, Nama);
            pst.setString(3, Alamat);
            pst.setString(4, Posisi);
            pst.setString(5, Ket);
            

            int k = pst.executeUpdate();
            System.out.println("Nilai executeUpdate" + k);
            if (k == 1 && IDStaff != "") {
                //Menampilkan Box keberhasilan saat mengupdate data
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan Staff baru");
                //Clear Data yang ada di box
//                jTextField5.setText("");
                id_auto();
                txtKeterangan.setText("");
                txtPosisi.setText("");
                txtAlamat.setText("");
                txtNama.setText("");
                txtNama.requestFocus();
                
               
            } else {
                //HMMM KOK INI GAK GUNA YAA :v padahal logikanya bisa
                JOptionPane.showMessageDialog(this, "Record Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jLabelSignMouseClicked

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtAlamat.requestFocus();
        }
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPosisi.requestFocus();
        }
    }//GEN-LAST:event_txtAlamatKeyPressed

    private void txtPosisiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPosisiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtKeterangan.requestFocus();
        }
    }//GEN-LAST:event_txtPosisiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClear;
    private javax.swing.JLabel jLabelMasuk;
    private javax.swing.JLabel jLabelSign;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIDStaff;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPosisi;
    // End of variables declaration//GEN-END:variables
}
