/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tbd;

import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class Lokasi extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    ResultSet RsProduk=null;
    /**
     * Creates new form Lokasi
     */
    public Lokasi() {
        initComponents();
        Connect();
        LocationTable();
    }
    Connection conn;
    Statement stmt;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtIDLok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonTambah = new javax.swing.JButton();
        txtKeterangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaLok = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        jButton1ClearData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 235, 205));

        jPanel3.setBackground(new java.awt.Color(255, 235, 205));

        jPanel2.setBackground(new java.awt.Color(255, 235, 205));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Form Lokasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(139, 69, 19))); // NOI18N

        txtIDLok.setBackground(new java.awt.Color(255, 248, 220));
        txtIDLok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDLokActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(139, 69, 19));
        jLabel3.setText("Keterangan");

        jButtonTambah.setBackground(new java.awt.Color(244, 164, 96));
        jButtonTambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\TBD\\src\\images\\icons8-add-24.png")); // NOI18N
        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        txtKeterangan.setBackground(new java.awt.Color(255, 248, 220));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 69, 19));
        jLabel4.setText("Status");

        txtNamaLok.setBackground(new java.awt.Color(255, 248, 220));

        jButtonDelete.setBackground(new java.awt.Color(244, 164, 96));
        jButtonDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\TBD\\src\\images\\icons8-delete-24 (1).png")); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        txtStatus.setBackground(new java.awt.Color(255, 248, 220));

        jButton1ClearData.setBackground(new java.awt.Color(244, 164, 96));
        jButton1ClearData.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\TBD\\src\\images\\icons8-eraser-24.png")); // NOI18N
        jButton1ClearData.setText("Clear");
        jButton1ClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ClearDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(139, 69, 19));
        jLabel1.setText("ID Lokasi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(139, 69, 19));
        jLabel2.setText("Nama Lokasi");

        jButtonUpdate.setBackground(new java.awt.Color(244, 164, 96));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\NetBeansProjects\\TBD\\src\\images\\icons8-update-24.png")); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDLok)
                            .addComponent(txtNamaLok)
                            .addComponent(txtKeterangan)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1ClearData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDLok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaLok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButton1ClearData))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addGap(27, 27, 27))
        );

        jPanel1.setBackground(new java.awt.Color(255, 235, 205));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Database Lokasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(139, 69, 19))); // NOI18N

        jButtonClear.setBackground(new java.awt.Color(244, 164, 96));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(244, 164, 96));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Lokasi", "Nama Lokasi", "Keterangan", "Status" }));

        jTable1.setBackground(new java.awt.Color(255, 235, 205));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Lokasi", "Nama Lokasi", "Keterangan", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtSearch.setBackground(new java.awt.Color(255, 248, 220));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(244, 164, 96));
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonClose.setBackground(new java.awt.Color(244, 164, 96));
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void Connect() {
        String url = "jdbc:jtds:sqlserver://127.0.0.1:1433/SmartParking"; //buka =  nama database yang digunakan 
        try {       
            conn = DriverManager.getConnection(url, "kelompok3", "semangat");
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void cariData(String key){
        try{
            Object[] judul_kolom = {"ID Lokasi", "Nama Lokasi", "Keterangan", "Status"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            jTable1.setModel(tabModel);
            
//            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsProduk=stt.executeQuery("SELECT * from Lokasi WHERE IDLokasi LIKE '%"+key+"%' OR NamaLokasi LIKE '%"+key+"%' OR Keterangan LIKE '%"+key+"%' OR Status LIKE '%"+key+"%'");  
            while(RsProduk.next()){
                Object[] data={
                    RsProduk.getString("IDLokasi"),
                    RsProduk.getString("NamaLokasi"),
                    RsProduk.getString("Keterangan"),
                    RsProduk.getString("Status")       
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    //Method menampilkan data di Tabel GUI
    public void LocationTable() {
        try {
            pst = conn.prepareStatement("select * from Lokasi where Deleted=0");
            rs = pst.executeQuery();
            //Deklarasi object yang berperilaku untuk memanggil meta data table
            ResultSetMetaData RSM = rs.getMetaData();
            int c = RSM.getColumnCount();
            DefaultTableModel DF = (DefaultTableModel) jTable1.getModel();
            DF.setRowCount(0);

            //Memasukkan data SQL ke Table GUI
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("IDLokasi"));
                    v2.add(rs.getString("NamaLokasi"));
                    v2.add(rs.getString("Keterangan"));
                    v2.add(rs.getString("Status"));
                   
                }
                DF.addRow(v2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        try {
                Class.forName("net.sourceforge.jtds.jdbc.Driver");
                String url = "jdbc:jtds:sqlserver://127.0.0.1:1433/SmartParking"; 
                Connection koneksi = DriverManager.getConnection(url, "kelompok3", "semangat"); 
                String sql = "SELECT * FROM Lokasi where Deleted = '0'";
                Statement state = koneksi.createStatement();
                //it will return a result set
                ResultSet rs = state.executeQuery(sql);
                
                ResultSetMetaData rsmetadata = rs.getMetaData();
                //it stores the number of columns
                int columns = rsmetadata.getColumnCount();
                
                DefaultTableModel dtn = new DefaultTableModel();
                Vector columns_name = new Vector();
                Vector data_rows = new Vector();
                
                for(int i=1; i< columns; i++){
                    columns_name.addElement(rsmetadata.getColumnName(i));    
                }
                dtn.setColumnIdentifiers(columns_name);
                
                while(rs.next()){
                    
                    data_rows = new Vector();
                    for(int j=1; j<columns; j++){
                    data_rows.addElement(rs.getString(j));
                    
                    }
                    dtn.addRow(data_rows);
                }
                txtSearch.setText("");
                jTable1.setModel(dtn);
            }
        catch (Exception e){
        }
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void txtIDLokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDLokActionPerformed
        try
            {
                pst = conn.prepareStatement("select * from Lokasi where IDLokasi='"+txtIDLok.getText()+"'");
//                st=con.createStatement();
//                rs=pst.executeQuery(sql);
                  rs = pst.executeQuery();

                while(rs.next())
                {
                    txtNamaLok.setText(rs.getString("NamaLokasi"));
                    txtKeterangan.setText(rs.getString("Keterangan"));
                    txtStatus.setText(rs.getString("Status"));
                    
                   
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"GAGAL");
            }
    }//GEN-LAST:event_txtIDLokActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        String IDLokasi = txtIDLok.getText();
        String NamaLok = txtNamaLok.getText();
        String Ket = txtKeterangan.getText();
        String Status = txtStatus.getText();
        
        if(txtIDLok.getText().equals("") || txtNamaLok.getText().equals("") || txtKeterangan.getText().equals("") || txtStatus.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Masukkan data secara lengkap!");
        else {
        try {
            pst = conn.prepareStatement("update Lokasi set NamaLokasi=?, Keterangan=?, Status=? where IDLokasi=?");
            pst.setString(1, NamaLok);
            pst.setString(2, Ket);
            pst.setString(3, Status);
            pst.setString(4, IDLokasi);

            int k = pst.executeUpdate();
            System.out.println("Nilai executeUpdate" + k);
            if (k == 1) {
                //Menampilkan Box keberhasilan saat mengupdate data
                JOptionPane.showMessageDialog(this, "Data diupdate");
                txtIDLok.setText("");
                txtNamaLok.setText("");
                txtKeterangan.setText("");
                txtStatus.setText("");
                txtIDLok.requestFocus();
                //Agar Tabel di kanannya terupdate (view ulang)
                LocationTable();
            } else {
                //HMMM KOK INI GAK GUNA YAA :v padahal logikanya bisa                JOptionPane.show
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButton1ClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ClearDataActionPerformed
                txtIDLok.setText("");
                txtNamaLok.setText("");
                txtKeterangan.setText("");
                txtStatus.setText("");
                txtIDLok.requestFocus();
                //Agar Tabel di kanannya terupdate (view ulang)
                LocationTable();
    }//GEN-LAST:event_jButton1ClearDataActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if(txtIDLok.getText().equals("") || txtNamaLok.getText().equals("") || txtKeterangan.getText().equals("") || txtStatus.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Masukkan data secara lengkap!");
        else { 
        try {
            String IDLokasi = txtIDLok.getText();
            pst = conn.prepareStatement("update Lokasi set Deleted=1 where IDLokasi=?");
            
            pst.setString(1, IDLokasi);
            //Query 
//            pst = conn.prepareStatement("delete from Staff where IDStaff=?");
////            pst.setString(1, "IDStaff");
//            pst.setString(1, bookno);
            //
            
            int k = pst.executeUpdate();
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Data telah dihapus");
                txtIDLok.setText("");
                txtNamaLok.setText("");
                txtKeterangan.setText("");
                txtStatus.setText("");
                txtIDLok.requestFocus();
                //Agar Tabel di kanannya terupdate (view ulang)
                LocationTable();
            
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus");
            }

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        HalamanUtama Beranda = new HalamanUtama();
        Beranda.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String ComboItem = jComboBox1.getSelectedItem().toString();
        String Keyword = txtSearch.getText();
        //txtSearch.setText(jComboBox1.getSelectedItem().toString());

        //Dari Code Tabel untuk menampilkan data di tabel
        try {
            //Karena Combo boxnya ada beberapa pilihan dan perlu querynya bergantung ke sana perlu dibikin if else statements
            if (ComboItem == "ID Lokasi") {
                pst = conn.prepareStatement("select * from Lokasi where IDLokasi = ? and Deleted=0 ");
            } else if (ComboItem == "Nama Lokasi") {
                pst = conn.prepareStatement("select * from Lokasi where NamaLokasi = ? and Deleted=0 ");
            } else if (ComboItem == "Keterangan") {
                pst = conn.prepareStatement("select * from Lokasi where Keterangan= ? and Deleted=0 ");
            } else if (ComboItem == "Status") {
                pst = conn.prepareStatement("select * from Lokasi where Status = ? and Deleted=0 ");
            } 
            pst.setString(1, Keyword);
            rs = pst.executeQuery();

            //Deklarasi object yang berperilaku untuk memanggil meta data table
            ResultSetMetaData RSM = rs.getMetaData();
            int c = RSM.getColumnCount();
//            JOptionPane.showMessageDialog(this, "Nilai Combo Item yg terpilih " + ComboItem);
            DefaultTableModel DF = (DefaultTableModel) jTable1.getModel();
            DF.setRowCount(0);

            //Memasukkan data SQL ke Table GUI
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("IDLokasi"));
                    v2.add(rs.getString("NamaLokasi"));
                    v2.add(rs.getString("Keterangan"));
                    v2.add(rs.getString("Status"));

                }
                DF.addRow(v2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        int SelectIndex = jTable1.getSelectedRow();

        //Agar saat dipilih data di table langsung muncul di Baris2 yang ada di Text
        String bookno = d1.getValueAt(SelectIndex, 0).toString();

        txtIDLok.setText(d1.getValueAt(SelectIndex, 0).toString());
        txtNamaLok.setText(d1.getValueAt(SelectIndex, 1).toString());
        txtKeterangan.setText(d1.getValueAt(SelectIndex, 2).toString());
        txtStatus.setText(d1.getValueAt(SelectIndex, 3).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        String IDLokasi = txtIDLok.getText();
        String NamaLokasi = txtNamaLok.getText();
        String Keterangan = txtKeterangan.getText();
        String Status = txtStatus.getText();
       
       if(txtIDLok.getText().equals("") || txtNamaLok.getText().equals("") || txtKeterangan.getText().equals("") || txtStatus.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Masukkan data secara lengkap!");
        else {
        try {
            pst = conn.prepareStatement("insert into Lokasi(IDLokasi, NamaLokasi, Keterangan, Status, Deleted)values(?,?,?,?,0)");
            pst.setString(1, IDLokasi);
            pst.setString(2, NamaLokasi);
            pst.setString(3, Keterangan);
            pst.setString(4, Status);
                   

            int k = pst.executeUpdate();
            System.out.println("Nilai executeUpdate" + k);
            if (k == 1 && IDLokasi != "") {
                //Menampilkan Box keberhasilan saat mengupdate data
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan Lokasi baru");
                //Clear Data yang ada di box
//                jTextField5.setText("");
               
                txtIDLok.setText("");
                txtNamaLok.setText("");
                txtKeterangan.setText("");
                txtStatus.setText("");
                txtIDLok.requestFocus();
                LocationTable();
               
            } else {
                //HMMM KOK INI GAK GUNA YAA :v padahal logikanya bisa
                JOptionPane.showMessageDialog(this, "Record Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String key=txtSearch.getText();
//        System.out.println(key);
        
        if(key!=""){
            cariData(key);
        }
        else{
            LocationTable();
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lokasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ClearData;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIDLok;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNamaLok;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
