/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tbd;
import java.awt.Desktop.Action;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.*;
import javax.swing.AbstractAction;

/**
 *
 * @author Asus
 */
public class Masuk extends javax.swing.JFrame {
private Connection kon;
public static String idStaff;
//    String idStaff;
    /**
     * Creates new form Masuk
     */
    public Masuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDStaff = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        labLogin = new javax.swing.JLabel();
        labSignup = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDStaff.setBackground(new java.awt.Color(184, 51, 48));
        txtIDStaff.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtIDStaff.setForeground(new java.awt.Color(255, 255, 255));
        txtIDStaff.setBorder(null);
        txtIDStaff.setOpaque(false);
        txtIDStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDStaffActionPerformed(evt);
            }
        });
        txtIDStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDStaffKeyPressed(evt);
            }
        });
        getContentPane().add(txtIDStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 180, 20));

        txtPassword.setBackground(new java.awt.Color(184, 51, 48));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 210, -1));

        labLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labLoginMouseClicked(evt);
            }
        });
        getContentPane().add(labLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 120, 30));

        labSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labSignupMouseClicked(evt);
            }
        });
        getContentPane().add(labSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\Purple and Pink Flat Color Login (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDStaffActionPerformed

    private void labLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLoginMouseClicked
       idStaff = txtIDStaff.getText();
       String value1=txtIDStaff.getText();
       String value2= String.valueOf(txtPassword.getPassword());
       String user1="";
       String pass1="";
        
        try {
        Class.forName("net.sourceforge.jtds.jdbc.Driver");
        String url = "jdbc:jtds:sqlserver://127.0.0.1:1433/SmartParking";
        Connection kon = DriverManager.getConnection(url, "kelompok3", "semangat");
        
        PreparedStatement stmt = kon.prepareStatement("SELECT * FROM Staff where IDStaff='"+value1+"'" +"and Deleted='0'");
            ResultSet res = stmt.executeQuery();
//            res = stmt.executeQuery();
            
            while (res.next()) {
                user1 = res.getString("IDStaff");
                pass1 = "semangat";
            }
            if(txtIDStaff.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Masukkan ID Staff");
            else if(txtPassword.getPassword().equals(""))
                JOptionPane.showMessageDialog(null,"Masukkan Password");
            else if (value1.equals(user1) && value2.equals(pass1)) {
            JOptionPane.showMessageDialog(this,"correct");
            new HalamanUtama().setVisible(true);
            dispose();
            }
            else if (value1.equals(user1) || value2.equals(pass1)){
            JOptionPane.showMessageDialog(this,"Incorrect ID Staff or password","Error",JOptionPane.ERROR_MESSAGE);
            txtIDStaff.setText("");
            txtPassword.setText("");
            txtIDStaff.requestFocus();
            }
            else {
            JOptionPane.showMessageDialog(this,"Anda belum terdaftar, silahkan Sign Up","Error",JOptionPane.ERROR_MESSAGE);
            new DaftarStaff().setVisible(true);
            dispose();
            }
        
    } 
    catch (ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
}
    }//GEN-LAST:event_labLoginMouseClicked

    private void labSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labSignupMouseClicked
        DaftarStaff obj = new DaftarStaff();
        this.setVisible(false);
        obj.setVisible(true);
    }//GEN-LAST:event_labSignupMouseClicked

    private void txtIDStaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDStaffKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtIDStaffKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
       
    }//GEN-LAST:event_txtPasswordKeyPressed

//    public static global(){
//        public static String idStaff = txt
//    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labLogin;
    private javax.swing.JLabel labSignup;
    private javax.swing.JTextField txtIDStaff;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
